login:
    type: rest
    resource: AppBundle\Controller\RestLoginController

profile:
    type: rest
    resource: AppBundle\Controller\RestProfileController

password_management:
    type: rest
    resource: AppBundle\Controller\RestPasswordManagementController